### ISSUE TITLE
关于Pression和Recall的问题，代码中应当是计算反了

### ISSUE THREAD

**Issue by CaiQiuYu** [Zhongdao/gcn_clustering#15]
这个问题我也有点晕乎，反复确认了一下，代码中bcubed那个函数，reference应当是GT，system应当是predict。麻烦作者你再确认一下。
比如GT为[0, 0, 0, 1, 1, 1],预测为[0, 0, 0, 0, 0, 0]。这样precision应当是0.5，recall是1，但是你的代码算出来recall 0.5，precision 为1.

**Comment by Zhongdao** [comment]
感谢提醒！确实是反了，已修正
